-module(e2).
-export([solve/0,fib/1]).

% Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

solve()->
  lists:sum(
    lists:filter(
      fun(X) -> (X rem 2 == 0) end,
      fib(4000000)
    )
  ).

fib(N) ->
  fib(N,1,2,[]).

fib(N,Current,_,Acc) when Current > N -> Acc;
fib(N,Current,Next,Acc) ->
  fib(N, Next, Current + Next, [Current|Acc]).
