{-Each new term in the Fibonacci sequence is generated by adding the previous
  two terms. By starting with 1 and 2, the first 10 terms will be:-}

{-1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...-}

{-By considering the terms in the Fibonacci sequence whose values do not exceed
  four million, find the sum of the even-valued terms.-}

{-import Data.List-}
import Data.Sequence as Seq

fib current next accum =
  if current > 4000000 then accum
  else fib (next) (current + next) (accum |> next)

evenFibs = Seq.filter even (fib 1 2 empty)
evenFibsSum = sum evenFibs

main = putStrLn $ show $ evenFibsSum
{-main = putStrLn $ show $ evenFibsSum 10-}
{-main = putStrLn $ show $ evenFibs 10-}
